/Users/livionmbp/opt/anaconda3/envs/cleanrl/lib/python3.9/site-packages/gym/core.py:172: DeprecationWarning: [33mWARN: Function `env.seed(seed)` is marked as deprecated and will be removed in the future. Please use `env.reset(seed=seed) instead.
  deprecation(
Traceback (most recent call last):
  File "/Users/livionmbp/Documents/GitHub/Sources/3DGridWorld/PPOagent.py", line 212, in <module>
    next_obs, reward, done, info = envs.step(action.cpu().numpy())
  File "/Users/livionmbp/opt/anaconda3/envs/cleanrl/lib/python3.9/site-packages/gym/vector/vector_env.py", line 112, in step
    return self.step_wait()
  File "/Users/livionmbp/opt/anaconda3/envs/cleanrl/lib/python3.9/site-packages/gym/vector/sync_vector_env.py", line 144, in step_wait
    self.observations = concatenate(
  File "/Users/livionmbp/opt/anaconda3/envs/cleanrl/lib/python3.9/functools.py", line 888, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/Users/livionmbp/opt/anaconda3/envs/cleanrl/lib/python3.9/site-packages/gym/vector/utils/numpy_utils.py", line 53, in _concatenate_base
    return np.stack(items, axis=0, out=out)
  File "<__array_function__ internals>", line 5, in stack
  File "/Users/livionmbp/opt/anaconda3/envs/cleanrl/lib/python3.9/site-packages/numpy/core/shape_base.py", line 433, in stack
    return _nx.concatenate(expanded_arrays, axis=axis, out=out)
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: Output array is the wrong shape